services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: artein_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - artein-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  # Aplicação para desenvolvimento
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: artein_app_dev
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      PORT: ${APP_PORT:-3001}
      JWT_SECRET: ${JWT_SECRET:-dev-secret-key}
      # Adicione outras variáveis de ambiente aqui
    ports:
      - "${APP_PORT:-3001}:3001"
    networks:
      - artein-network
    profiles:
      - dev
    # Removed automatic seeding from startup command
    command: sh -c "npx prisma migrate dev && npm run start:dev"

  # Aplicação para produção
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: artein_app_prod
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      PORT: ${APP_PORT:-3001}
      JWT_SECRET: ${JWT_SECRET}
      # Adicione outras variáveis de ambiente aqui
    ports:
      - "${APP_PORT:-3001}:3001"
    networks:
      - artein-network
    profiles:
      - prod
    # Fixed: Use node directly instead of npm start
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"

volumes:
  pgdata:

networks:
  artein-network:
    driver: bridge